# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 守真茗慧
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shouzhenminghui.com" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: 北京守真茗慧文化传播有限公司
address_line: 北京市平谷区中关村科技园区平谷园A区7号-21149
telephone_number:  15901534348
fax_number:
company_email: szmh_dev@126.com
google_map: https://www.google.com/maps/place/%E4%B8%AD%E5%9B%BD%E5%8C%97%E4%BA%AC%E5%B8%82%E4%B8%9C%E5%9F%8E%E5%8C%BA%E8%85%8A%E5%BA%93%E8%83%A1%E5%90%8C+%E9%82%AE%E6%94%BF%E7%BC%96%E7%A0%81:+100009/@39.92977,116.4013425,18z/data=!3m1!4b1!4m6!3m5!1s0x35f053271f253b21:0x17cc49a5fcfbb54e!8m2!3d39.92977!4d116.40263!16s%2Fg%2F1tfz_77q?hl=zh-cn

# Social Link
facebook_link: http://www.facebook.com
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
